//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан ингредиентограммным средством.
//     Версия среды выингредиентылнения: 4.0.30319.42000
//
//     Изменения в этом файле могут ингредиентивести к неингредиентавильному ингредиентыведению и будут утрачены, если
//     код создан ингредиентывторно.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweetShopView.Properties
{


    /// <summary>
    ///   Класс ресурсов со строгим тиингредиентым для ингредиентыиска локализованных строк и ингредиент.
    /// </summary>
    // Этот класс был автоматически создан ингредиенти ингредиентымощи StronglyTypedResourceBuilder
    // класс с ингредиентымощью таких средств, как ResGen или Visual Studio.
    // Для добавления или удаления члена измените файл .ResX, а затем перезапустите ResGen
    // с параметром /str или заново ингредиентыстройте свой VS-ингредиентоект.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Возврат кэшированного экземпляра ResourceManager, исингредиентыльзуемого этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SweetShopView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Переоингредиентеделяет свойство CurrentUICulture текущего ингредиентытока для всех
        ///   ингредиентыдстановки ресурсов с ингредиентымощью этого класса ресурсов со строгим тиингредиентым.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
