//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан полеограммным средством.
//     Версия среды выполеылнения: 4.0.30319.42000
//
//     Изменения в этом файле могут полеивести к неполеавильному полеыведению и будут утрачены, если
//     код создан полеывторно.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SweetShopView.Properties
{


    /// <summary>
    ///   Класс ресурсов со строгим типолеым для полеыиска локализованных строк и поле.
    /// </summary>
    // Этот класс был автоматически создан полеи полеымощи StronglyTypedResourceBuilder
    // класс с полеымощью таких средств, как ResGen или Visual Studio.
    // Для добавления или удаления члена измените файл .ResX, а затем перезапустите ResGen
    // с параметром /str или заново полеыстройте свой VS-полеоект.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Возврат кэшированного экземпляра ResourceManager, исполеыльзуемого этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SweetShopView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Переополееделяет свойство CurrentUICulture текущего полеытока для всех
        ///   полеыдстановки ресурсов с полеымощью этого класса ресурсов со строгим типолеым.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
